name: release

on:
  push:
    tags:
      - v?[0-9]+.[0-9]+.[0-9]+

permissions:
  contents: write

jobs:
  test:
    uses: ./.github/workflows/test.yml
  release:
    needs:
      - test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: release
        run: make -f .ci/Makefile release
        env:
          GITHUB_TOKEN: ${{ github.token }}
          TAG_NAME: ${{ github.ref_name }}
  notify:
    runs-on: ubuntu-latest
    if: always()
    needs:
      - release
    steps:
      - run: test $(echo '${{ toJSON(needs) }}' | jq -s 'map(.[].result) | all(.=="success")') = 'true'
      - if: always()
        uses: elastic/oblt-actions/slack/notify-result@v1
        with:
          bot-token: ${{ secrets.SLACK_BOT_TOKEN }}
          channel-id: "#apm-agent-php"
