name: release

on:
  push:
    tags:
      - v?[0-9]+.[0-9]+.[0-9]+

permissions:
  contents: write

jobs:
  test:
    uses: ./.github/workflows/test.yml
  release:
    needs:
      - test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: release
        run: make -f .ci/Makefile release
        env:
          GITHUB_TOKEN: ${{ github.token }}
          TAG_NAME: ${{ github.ref_name }}
  notify:
    runs-on: ubuntu-latest
    if: always()
    needs:
      - release
    steps:
      - run: test $(echo '${{ toJSON(needs) }}' | jq -s 'map(.[].result) | all(.=="success")') = 'true'
      - if: always()
        uses: elastic/apm-pipeline-library/.github/actions/notify-build-status@current
        with:
          vaultUrl: ${{ secrets.VAULT_ADDR }}
          vaultRoleId: ${{ secrets.VAULT_ROLE_ID }}
          vaultSecretId: ${{ secrets.VAULT_SECRET_ID }}
          slackChannel: "#apm-agent-php"
